### ISSUE TITLE
Config-server issue

### ISSUE THREAD

**Issue by salexstephen** [spring-cloud-services-samples/cook#8] opened 2016-12-02 14:34 UTC
i tried this sample and followed the steps mentioned in the 
https://docs.pivotal.io/spring-cloud-services/1-3/config-server/writing-client-applications.html

I got the below error and mainly it unable to bind the git property value with java variable in the client application.

OUT Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'cook.special' in string value "${cook.special}"

**Comment by cdavisafc** [comment] 2016-12-12 00:54
Yep, ran into that too. The issue is that the URL to the cook-config repo is incorrect in the deploy.sh file - it appears the repo was moved/org was renamed. Just issued a PR.

**Comment by abains** [comment] 2017-01-12 13:43
Is there an update on this issue?  What do I need to fix to get around it?

**Comment by cdavisafc** [comment] 2017-01-12 13:59
This pull request (https://github.com/spring-cloud-services-samples/cook/pull/9) fixes it. Basically, a URL needs to be updated - super simple fix.

The URL in line 8 of the scripts/deploy.sh file needs to be https://github.com/spring-cloud-services-samples/cook-config.

The PR hasn't been merged but you can make that change in your local copy yourself.

**Comment by royclarkson** [comment] 2018-06-07 15:55
This has been resolved in recent versions. Thanks for the feedback!

**Closed as completed by royclarkson** 2018-06-07 15:55 UTC
Labels: accepted
